version: 2.0.0
checkFullInventory: false

database:
  sqlite:
    path: ""
  mysql:
    enable: false
    url: "127.0.0.1:3306"
    database: xl2
    username: root
    password: 123456
    driver: "com.mysql.jdbc.Driver"
