#版本号
version: ${project.version}

#是否向玩家展示概率
showProbability: false
#是否显示粒子特效
enableParticle: true

#是否启用商店
shop: true
#商店是否给与玩家奖券，如果为false则直接进行抽奖。
giveLottery: true
#giveKey：当上面为true时，true为给与玩家抽奖箱钥匙，false为给与玩家奖券
giveKey: true

#自动保存的秒数
autoSaveTime: 120

#排行榜更新秒数
autoUpdateTopTime: 120
