#版本号
version: ${project.version}

#语言文本
lang: zh_CN.yml

#是否使用数据库
enableDatabase: false

#是否向玩家展示概率
showProbability: false
#是否显示粒子特效
enableParticle: true

#抽到保底是否播报
broadcast: true
#是否启用商店
shop: true
#商店是否给与玩家奖券，如果为false则直接进行抽奖。
giveLottery: true
#giveKey：当上面为true时，true为给与玩家抽奖箱钥匙，false为给与玩家奖券
giveKey: true

#自动保存的秒数 为0则取消自动保存， 在跨服请尽量避免跨服保存！ 有概率被子服覆盖导致更改失效
autoSaveTime: 0

#排行榜更新秒数
autoUpdateTopTime: 120

#默认抽奖记录保存次数,过多可能会占用大量磁盘空间
recordAmount: 500
