version: 2.0.1
checkFullInventory: false
#nms: 如果你不懂，就不要填
nms: ""
database:
  sqlite:
    path: ""
  mysql:
    enable: false
    url: "127.0.0.1:3306"
    database: xl2
    username: root
    password: 123456
    driver: "com.mysql.jdbc.Driver"
