  name: "XgpLottery2"
  main: "cn.xgpjun.xgplottery2.XgpLottery"
  version: ${version}
  api-version: "1.13"
  folia-supported: true
  authors: [ 1badsobig ]
  softdepend:
    - ParticleLib
    - PlaceholderAPI
    - Multiverse-Core
    - ProtocolLib
    - NeigeItems
  commands:
    xgplottery2:
      aliases:
        - "xl"
      usage: "plugin is disabled!"
