name: XgpLottery
version: ${project.version}
main: cn.xgp.xgplottery.XgpLottery
api-version: 1.13
authors: [ 1badsobig ]
description: A lottery plugin.

softdepend:
  - PlaceholderAPI
  - ParticleLib
  - PlayerPoints
  - Vault
commands:
  xgplottery:
    description: "XgpLottery's main command"
    aliases:
      - "xl"
      - "lottery"
    usage: "§cuse /xgplottery help for help"

permissions:
  xgplottery.manager:
    description: "allow to manage the plugin"
    default: op
  xgplottery.shop:
    description: "allow to open shop GUI"
    default: not op
  xgplottery.show:
    description: "allow to open show GUI"
    default: not op